name: Wealth Garden Wizard
favicon: null
layout_spectrum: 0.8913336817640811
typography_spectrum: 0.22848045080900192
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.07806712482124567
  lightness: 0.526540933875367
  saturation: 0.3964523586910218
  rhythmicContrast: 0.26931903697550297
purpose: []
